const express=require('express')
const cors=require('cors')
const app=express()
app.use(cors())
app.use(express.json())
app.use('/api',require('./routes/todoRoute'))
app.listen(3000,()=>console.log("3000 listening"))